name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: debuginfo
      run: echo ${{ github.sha }} ${{ env.REGISTRY }}
    - name: Build the Docker image
      #run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ github.sha }} --tag ${{ env.IMAGE_NAME }}:latest
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:latest
    - name: docker login
      run: docker login -u ${{ github.actor }} -p ${{ secrets.DOCKERHUB_TOKEN }} ${{ env.REGISTRY }}
    - name: docker push latest
      run: docker push --quiet ${{ env.REGISTRY }}${{ env.IMAGE_NAME }}:latest
    - name: docker push hash
      run: docker push --quiet ${{ env.REGISTRY }}${{ env.IMAGE_NAME }}:${{ github.sha }}
      
      
      
